---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Eyu.
--- DateTime: 2024/3/28 17:15
---
M = {}
function M:func()
    local b = A:new(nil,2,"b")
    print("-----------b:",b.a)
end